server:
  port: 8658 # 服务端口
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: car-finance-system # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/car-finance-system?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/yjp/carfinancesystem/mapper/xml/*.xml
